import React, { useState } from "react";
// import our data from the Javascript file.
// JSON object representing Spotify streams to August 2023
import { spotify2023 } from "./spotify2023";

// Writing our own functions for use in our app
// Writing a comment about a specific number.
function writeNumberAsWords(n) {
  let nAsStr = n.toString(10); // our number is in base 10
  let digits = nAsStr.length; // number of digits
  let firstDigit = nAsStr.charAt(0);

  let message = "nothing";
  if (digits === 9) {
    message = "(At least " + firstDigit + " hundred million!)";
  } else if (digits === 10) {
    message = "(At least " + firstDigit + " billion!)";
  } else {
    message = "(Lots of streams)";
  }

  return message;
}

// Parent component - App
// 1. create searchTerm using useState hook
// 2. obtain what user put in the search box each time using onSearchFormChange function
// 3. use props to pass the array and searchTerm to child component
function App() {
 
  const [searchTerm, setSearchTerm] = useState("");  
  // create the searchTerm as a state varaiable,given an initial value of empty string

  function onSearchFormChange(event) {   // Here is our textbox handler function. An event is generated by Javascript.
    setSearchTerm(event.target.value);  // We use the hook setSearchTerm to safely assign the current value in the textbox to searchTerm
  }

  return (
    <>
      <h1>Parent component CS385 Spotify Search</h1>
      <p>Your current search term is [{searchTerm}]</p>
      <form>
        <h3>Type your search here: </h3>
        <input onChange={onSearchFormChange} type="text" />  //this is where user input searchTerm
      </form>
      <hr />
      <ResultsComponent   //props to pass array and searchTerm to the child component
        searchTermFromParent={searchTerm}
        spotifyArrayFromParent={spotify2023}
      />
    </>
  );
}


// Child component - ResultsComponent
// 1. create a filter function to filter all objects include searchTerm
// 2. count the number of results after filter use .length
function ResultsComponent(props) {
  
  function spotifyFilterFunction(searchTerm) {  //filter function
    return function (spotifyObject) {
      let artist = spotifyObject.artist.toLowerCase();  // convert everything to lower case for string matching
      let track = spotifyObject.track.toLowerCase();
      return (
        searchTerm !== "" &&
        (track.includes(searchTerm.toLowerCase()) ||
          artist.includes(searchTerm.toLowerCase()))
      );
    };
  }

  let numberResults = props.spotifyArrayFromParent.filter(
    spotifyFilterFunction(props.searchTermFromParent)
  ).length;  // The length of filted array = numberResults

  
  return (
    <>
      <h1>Child Component: Search Results</h1>
      <h2>There are {numberResults} search results </h2>
      // show different text for different amount of results
      {numberResults === 0 && <p>No results</p>}
      {numberResults > 0 && numberResults < 10 && <p>Some results, not many</p>}
      {numberResults > 10 && <p>Lots of results</p>}
      //map function + filter function to show all the reaults filted
      {props.spotifyArrayFromParent
        .filter(spotifyFilterFunction(props.searchTermFromParent))  //filter function
        .map((a, index) => (  //map function
          <p key={index}>
            <b>{a.artist}</b>, <i>{a.track}</i> , Year: {a.release}, Streams: {a.streams}{" "}
            {writeNumberAsWords(a.streams)}
          </p>
        ))}
    </>
  );
} // end of child component for results.
export default App;
